### ISSUE TITLE
tag releases for semantic versioning

### ISSUE THREAD

**Issue by fortytw2** [StabbyCutyou/generics#1]
this is very important for people vendoring your code, see [this excellent article](http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases) for more information

**Comment by StabbyCutyou** [comment]
Thank you for bringing this to my attention. This is clearly an oversight.

I will release a proper semantically versioned tag of this package once I'm home tonight, as I am at my day job where it would be legally and morally inappropriate and reprehensible to work on a personal project such as this, even one for which I am extremely passionate about.

I implore you to be patient with me, and I promise you can begin using the semantically proper version of the package in no time!

**Comment by StabbyCutyou** [comment]
I would like to officially let you know that I have corrected my oversight.

The official v1.0.0 tag is up, and you can begin using it immediately!

Thanks again
