### ISSUE TITLE
Update for Go 1.8

### ISSUE THREAD

**Issue by ScottMansfield** [StabbyCutyou/generics#14]
I'm sure there's something that happened with unsafe and garbage collection that completely break everything in this project. You must root out the evils to stay compliant.

**Comment by StabbyCutyou** [comment]
I'll be releasing an official 1.8 update soon, you can rest assured!

**Comment by StabbyCutyou** [comment]
Dear Scott,

Please find attached to this comment a link which you can use to view a Pull Request wherein I am officially releasing G with both blessed support for later versions of 1.7, as well as the best version of go yet, 1.8.

Additionally, you'll find a series of new Benchmarks. These are rudimentary and a work in progress, so forgive them if they are not 100% accurate at this time, but I feel they give a good-enough estimate of the cost of using G in high performance code bases.

All the best,

Stabby

https://github.com/StabbyCutyou/generics/pull/16

**Comment by StabbyCutyou** [comment]
This is now merged into master.

Thankfully, this required no changes to the go code of package generics, and thus v1.0.0 still maintains 100% backwards and forwards compatibility.

Thank you for opening this issue
