### ISSUE TITLE
Please use semver releases

### ISSUE THREAD

**Issue by Dynom** [StabbyCutyou/generics#15]
With all the vendoring issues behind us, it's time for serious packages to get serious about the releases.

I think it's safe to say that `G` could start of with a `v1.0.0` release. We've been using it in production for many weeks, after we've thoroughly tested it with data from several weeks worth of Fuzzy corpuses.

**Comment by StabbyCutyou** [comment]
Thanks for the suggestion!

You should find that there already exists a v1.0.0 tag in the repo - if you're unable to use this with any of the golang vendoring and dependency managerial toolsets currently supported by the go team, please file an issue with those projects and tag me in them, so I can work with the authors to ensure full backwards compatibility.

Please ensure for me, before I close the issue, that you can browse this tag successfully via the GitHub Web User Interface, like so

<img width="417" alt="screen shot 2017-04-04 at 8 47 40 pm" src="https://cloud.githubusercontent.com/assets/1528618/24684947/168a1aa2-1978-11e7-97f3-2044058880f3.png">

Thanks for using `G`!

**Comment by Dynom** [comment]
Oh this is amazing!

My CEO (who's also the CFO, account manager and my cousin) assured me that it wasn't there, but I'm glad that this Github feature shows the 1.0 tag.

I can't express how well `G` works for us, thanks so much for your hard work and dedication to producing quality software.


Cheers,

Mark

**Comment by StabbyCutyou** [comment]
Thanks for saying it with G!
