### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by iitalics** [StabbyCutyou/generics#19]
For the good of the Internet, and in fact humanity, we need to migrate our software from Go to Rust (or something better) as quickly as possible. Here are some steps we need to take:

- Use Rust. Using Rust instead of Go makes code safer. Using Rust instead of any other language grows the Rust community, making it easier for other people to use Rust.
- Rewrite code in Rust. Starting with our most critical infrastructure, rewrite Go code to use Rust instead.
- Extend Rust's guarantees. We can extend the classes of bugs that Rust prevents. For example, we should try to make Rust release builds check for integer overflow by default.
- Verify "unsafe" Rust code. Sometimes the Rust type system is not strong enough to let you prove to the compiler that your code is safe, so you have to mark code blocks "unsafe". With tool support, you could instead generate a mathematical proof that your code is safe, checked by the compiler.

**Comment by StabbyCutyou** [comment]
I wouldn't be opposed to a Rust-themed fork of this project, however at this time I'm only interested in personally providing a solution for golang developing gophers around the world.

If you would like, I'm happy to consult on the project as a thought-leading architectural expert on the use of generics for small fee.

Thanks for interest in the project!
