### ISSUE TITLE
Add tests to actually test generics

### ISSUE THREAD

**Issue by nii236** [StabbyCutyou/generics#2]
Tests currently don't actually test

**Comment by StabbyCutyou** [comment]
Hello,

Thank you for taking the time to open an issue.

I want you, and the theoretical millions of golang developing gophers out there know that I am _firmly_ committed to quality tests in (what I hope will one day become the official) package generics.

I have already accepted an existing PR to improve my current tests, and I am working on a revised suite of tests as we speak, which will encompass a range of use cases for G.

Therefore, in the spirit of community cooperation and collaboration (which golang sets the gold standard for), I have decided to accept this Issue, but will not close it until the new tests are delivered to the community.

**Comment by StabbyCutyou** [comment]
As the tests have been improved, I am considering this matter solved.

Please open a new PR with additional tests if you feel they are warranted.
