### ISSUE TITLE
CI for this project?

### ISSUE THREAD

**Issue by nullbio** [StabbyCutyou/generics#7]
Hi, just wondering if you have any plans on adding CI to this. Here are a couple of popular options:

http://circleci.com/
https://travis-ci.org/

I think this will really help future contributors and is a great way to demonstrate to the open source community that -- despite the complexity of this package -- the testing story is well looked after.

Thank you.

**Comment by StabbyCutyou** [comment]
This is a great idea!

I'll work on this immediately

**Comment by fortytw2** [comment]
@StabbyCutyou it's important to test on a variety of CI systems to ensure cross platform compatibility. I'd recommend at least 5 different ones to be safe

**Comment by StabbyCutyou** [comment]
That's a good point. We cannot allow a false positive on any one CI system
to mislead us about the sanctity of these tests.

Can you recommend other free CI systems, and I can add backlog tasks to add
more in, once Travis is passing?

**Comment by StabbyCutyou** [comment]
I've integrated Travis into the build. If anyone has further suggestions, please continue to open issues.
