### ISSUE TITLE
Test alias types byte and rune

### ISSUE THREAD

**Issue by heppu** [StabbyCutyou/generics#9]
Even though byte is alias for uin8 and rune is alias for int32 I think it is really important to test these too.

**Comment by StabbyCutyou** [comment]
I agree 100%. This is a considerable oversight from the current testing package.

I can add these in tonight, but PRs are welcome as well!

Thank you for your involvement with the project

**Comment by StabbyCutyou** [comment]
Issue is closed with the merging of your excellent PR
